server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-route
          # 负载均衡，动态路由
          uri: lb://oauth2-server
          predicates:
            - Path=/auth/**
        - id: user-route
          # 负载均衡，动态路由
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: Hystrix
              args:
                name: fetchIngredients
                # 优先找网关的跳转端点
                fallbackUri: forward:/fallback
        # 如果网关没有forward:/fallback的端点，那么可以指定存在跳转端点的位置
        - id: ingredients-fallback
          uri: http://localhost:9092
          predicates:
            - Path=/fallback
        - id: product-route
          # 负载均衡，动态路由
          uri: lb://product-service
          predicates:
            - Path=/product/**


#设置hystrix的熔断时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #设置API网关中路由转发请求的HystrixCommand执行超时时间
            timeoutInMilliseconds: 5000