server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:9091
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: user-route
          uri: http://localhost:9092
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: product-route
          uri: http://localhost:9093
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1