server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:9091
          predicates:
            - Path=/auth/**
        - id: user-route
          uri: http://localhost:9092
          predicates:
            - Path=/user/**
        - id: product-route
          uri: http://localhost:9093
          predicates:
            - Path=/product/**

