server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-route
          # 负载均衡，动态路由
          uri: lb://oauth2-server
          predicates:
            - Path=/auth/**
        - id: user-route
          # 负载均衡，动态路由
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: product-route
          # 负载均衡，动态路由
          uri: lb://product-service
          predicates:
            - Path=/product/**

